// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADTDjFtf7Mt9_0QffgsIGvJmpNZDnNgMg',
    appId: '1:1039684510728:web:1d3f0f70bc0078b637ddbd',
    messagingSenderId: '1039684510728',
    projectId: 'flutchatsend',
    authDomain: 'flutchatsend.firebaseapp.com',
    databaseURL: 'https://flutchatsend-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutchatsend.firebasestorage.app',
    measurementId: 'G-PHRCPZQCCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAee10uQLkL3980XOdWFYEJ-MnJ9vytSyA',
    appId: '1:1039684510728:android:920e5254e62c483037ddbd',
    messagingSenderId: '1039684510728',
    projectId: 'flutchatsend',
    databaseURL: 'https://flutchatsend-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutchatsend.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADTDjFtf7Mt9_0QffgsIGvJmpNZDnNgMg',
    appId: '1:1039684510728:web:7948bbcd06d41e4937ddbd',
    messagingSenderId: '1039684510728',
    projectId: 'flutchatsend',
    authDomain: 'flutchatsend.firebaseapp.com',
    databaseURL: 'https://flutchatsend-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutchatsend.firebasestorage.app',
    measurementId: 'G-Y0PVCGDBZ6',
  );
}
